name: Semantic Pull Request
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
permissions:
  pull-requests: read
  contents: read # Needed to fetch the .gitattributes file if present
jobs:
  main:
    name: Validate PR Title
    runs-on: ubuntu_latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.5 # Pinned to minor version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}" should not start with a capital letter. This is to follow conventional commit style guidelines. Please use lowercase for the first letter of the subject.
          types: |
            fix
            feat
            chore
            build
            ci
            perf
            docs
            refactor
            revert
            test
